### ISSUE TITLE
Can a modifier on an element affect other elements of the same block nested within it?

### ISSUE THREAD

**Issue by artinboghosian** [getbem/getbem.com#102]
Let's say I have a calendar block with following markup

<div class="calendar">
  <div class="calendar__row">
     <div class="calendar__cell">
       <a class="calendar__day">25</a>
     </div>
  </div>
</div>

If i added modifier to calendar_cell, say calendar__cell--future, would BEM allow modifying the calendar__day element as a result?

**Comment by manumorante** [comment]
Hi @artinboghosian!
I'm not sure if BEM say something about this but I prefer use the common inherited as usual.

```scss
// --(Modifier) Future Calendar Cell
.calendar__cell--future {
  background-color: #aff;

  // --(Inherited modifier) Future Calendar Cell Day
  .calendar__day {
    background-color: #0aa;
    color: #fff;
  }
}
```

Here I created a visual example:
http://codepen.io/unavezfui/pen/BzOrGZ
