### ISSUE TITLE
Should I define a variant or there's some better way?

### ISSUE THREAD

**Issue by FezVrasta** [getbem/getbem.com#79]
I have two components:

```less
.button {
  &--primary {
    color: red;
  }
  &--default {
    color: black;
  }
}

.header {
  background: black;
}
```

Now, my HTML is:

```html
<header class=header>
  <button class="button button--default">
</header>
```

Inside my header, the default button will not be visible, because the background has the same color of the text.

I'd like to do something like this:

```less
.header {
  background: black;
  &__button {
    color: white;
  }
}
```

```html
<header class=header>
  <button class="header__button button button--default">
</header>
```

But it doesn't look so BEMish...

I think the other solution would be to define a variant of `.button` for just this specific case, but I wanted to check if there is some easier way for this specific case?

Thanks.

**Comment by garrypolley** [comment]
My usual go-to here is a `button--inverse`. So it'd look something like this with the current setup you  have: 

```less
.button {
  &--primary {
    color: red;
  }
  &--default {
    color: black;
  }
  &--inverse {
    color: white;
  }
}

.header {
  background: black;
}
```

If it has special meaning _only_ in a header then a new component could make sense. Based on what I see I'd favor making a `button--inverse`.
