### ISSUE TITLE
Global component theming issue

### ISSUE THREAD

**Issue by FezVrasta** [getbem/getbem.com#80]
I have this LESS:

```less
.foo-bar {
  &__el1 {
    height: 10px;
  }
  &__el2 {
    height: 15px;
  }
  &__el3 {
    height: 10px;
  }
}
```

now... I want to add some theming variations to it:

```less
&--sm {
  // here something to change the height of my 3 elements...
}```

Obviously I don't want to apply the `--sm` variation to each element of my component, but I want to add it just to the component and changing the rest accordingly.

How to proceed?
